-- 补充 products 表缺少的字段
ALTER TABLE products ADD COLUMN IF NOT EXISTS material TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS origin TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS diameter TEXT DEFAULT '10mm';
ALTER TABLE products ADD COLUMN IF NOT EXISTS gradient TEXT DEFAULT '';
